user_id: <username>
group_id: "docker"

# Enviroment directory created at installation include docker-compose.yml

# Becarefull as name used by docker-compose and used for urls
env_path: "/home/{{user_id}}/environment"

# Data and log path
log_path: "/home/{{user_id}}/log"
data_path: "/home/{{user_id}}/data"

# Pipeline
pipeline_path: "/home/{{user_id}}/pipeline"
pipeline_conf: "/home/{{user_id}}/environment/pipeline.conf"
pipeline_log: "/home/{{user_id}}/log/pipeline.log"
pipeline_pem: "/home/{{user_id}}/environment/pig"
pipeline_dump: "/home/{{user_id}}/log/dump.txt"
dump_path_config: "file = log/dump.txt"

# Influx
url: "http://localhost:3000"
username: "admin"
password: "admin"
data_source: "InfluxDB"
url_data_source: "http://environment_influxdb_1:8086"

